# -*- coding: utf-8 -*-
"""Text3Speech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mr6CohagF-oRnEpW1j230Ot6X91E_P4e
"""

import streamlit as st
import openai
from gtts import gTTS
import os

# Initialize OpenAI client
openai.api_key = st.secrets["OPENAI_API_KEY"]

st.title("🎙️ Text2Speech ChatBot")

from gradio_client import Client

client = Client("NihalGazi/Text-To-Speech-Unlimited")
result = client.predict(
		prompt="Hello! What a splendid outing today!",
		voice="alloy",
		emotion="happy",
		use_random_seed=True,
		specific_seed=12345,
		api_name="/text_to_speech_app"
)
print(result)
